apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-application
  namespace: uat
spec:
  template:
    metadata:
      labels:
        app: logstash-application
    spec:
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
      - name: acs-access
      containers:
      - image: coeoctava.azurecr.io/logstash:v1.0.0
        name: logstash-application
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash-pipeline.conf
        resources:
          requests:
            memory: 1Gi
            cpu: "200m"
          limits:
            memory: 2Gi
            cpu: "200m"
      - name: proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
            "-instances=octavia-189116:us-west1:loggit-db=tcp:3306",
            "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: proxy-service-account	
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: pipeline
        secret:
          secretName: logstash-pipeline
      - name: config
        configMap:
          name: logstash-application
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: proxy-service-account
        secret:
          secretName: octavadb-service-account  