apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-application
  namespace: uat
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false