version: '3.4'

services:
  issues-server:
    image: ${DOCKER_REGISTRY}issuesserver
    depends_on: 
      - wordpress-db
    build:
      context: .
      dockerfile: issues-server/issues-server/Dockerfile

  ideas-server:
    image: coeoctava.azurecr.io/initiatives-webapi:dev-1.0.3463
    depends_on: 
      - wordpress-db

  wordpress-db:
    image: coeoctava.azurecr.io/wordpress-db:v1.0.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: octavadev
      MYSQL_DATABASE: octportalwordpress

  issues-integration-remedy:
    image: ${DOCKER_REGISTRY}issuesintegrationremedy
    build:
      context: .
      dockerfile: issues-integration-remedy/Dockerfile


  issues-integration-remedy-watcher:
    image: ${DOCKER_REGISTRY}issuesintegrationremedywatcher
    build:
      context: .
      dockerfile: issues-integration-remedy-watcher/Dockerfile


  issues-integration-remedy-sblistener:
    image: ${DOCKER_REGISTRY}issuesintegrationremedysblistener
    build:
      context: .
      dockerfile: issues-integration-remedy-sblistener/Dockerfile

  initiatives-vue:
    image: coeoctava.azurecr.io/initiatives-vue:dev-1.0.3463
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ../../plugins/ideas/:/app   

  wordpress:
    depends_on: 
      - wordpress-db
    image: coeoctava.azurecr.io/wordpress:v1.0.3
    ports:
      - "8000:80"
      - "9000:9000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: octportalwordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: octavadev

  nginx:
    depends_on:
      - wordpress
      - issues-server
      - initiatives-vue
    image: coeoctava.azurecr.io/nginx:v1.0.3463
    restart: always
    ports:
      - "80:80"