version: '3.4'

services:
  issues-server:
    image: ${DOCKER_REGISTRY}issuesserver
    build:
      context: .
      dockerfile: issues-server/issues-server/Dockerfile

  wordpress-db:
    image: coeoctava.azurecr.io/wordpress-db:v1.0.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: octavadev
      MYSQL_DATABASE: octportalwordpress

  issues-integration-remedy:
    image: ${DOCKER_REGISTRY}issuesintegrationremedy
    build:
      context: .
      dockerfile: issues-integration-remedy/Dockerfile


  issues-integration-remedy-watcher:
    image: ${DOCKER_REGISTRY}issuesintegrationremedywatcher
    build:
      context: .
      dockerfile: issues-integration-remedy-watcher/Dockerfile


  issues-integration-remedy-sblistener:
    image: ${DOCKER_REGISTRY}issuesintegrationremedysblistener
    build:
      context: .
      dockerfile: issues-integration-remedy-sblistener/Dockerfile

  initiatives-vue:
    image: coeoctava.azurecr.io/initiatives-vue:dev-1.0.0
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./plugins/ideas/:/app   