apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
    product: octava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      product: octava
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        product: octava
    spec:
      containers:
      - name: wordpress
        image: coeoctava.azurecr.io/wordpress:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-db:3306"
        - name: WORDPRESS_DB_NAME
          value: "OctPortalWordPress"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: "octavadev"
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: wordpress-config