version: '3'

services:
  ideas-server:
    image: ideasserver
    depends_on: 
      - initiatives-db
    build:
      context: .
      dockerfile: ideas-server/ideas-server/Dockerfile

  wordpress-db:
    image: coeoctava.azurecr.io/wordpress-db:v1.0.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: octavadev
      MYSQL_DATABASE: octportalwordpress


  initiatives-db:
    image: coeoctava.azurecr.io/initiatives-db:v1.0.2
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: OctavaDev100!
      MSSQL_PID: Developer

  wordpress:
    depends_on: 
      - wordpress-db
    image: coeoctava.azurecr.io/wordpress:latest
    ports:
      - "8000:80"
      - "9000:9000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: octportalwordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: octavadev

  initiatives-vue:
    image: coeoctava.azurecr.io/initiatives-vue:vs-1.0.0
    ports:
      - "8080:8080"
    volumes: 
      - ../plugins/ideas:/app

  nginx:
    depends_on:
      - wordpress
      - ideas-server
      - initiatives-vue
    image: coeoctava.azurecr.io/nginx:dev-latest
    restart: always
    ports:
      - "80:80"


  ideas-integration-remedy:
    image: ideasintegrationremedy
    build:
      context: .
      dockerfile: ideas-integration-remedy/ideas-integration-remedy/Dockerfile

  ideas-integration-remedy-sblistener:
    image: ideasintegrationremedysblistener
    build:
      context: .
      dockerfile: ideas-integration-remedy/ideas-integration-remedy-sblistener/Dockerfile
