apiVersion: v1
kind: Service
metadata:
  name: wordpress-db
  labels:
    app: wordpress-db
    technology: mysql
    product: octava
    tier: backend
spec:
  type: ExternalName
  externalName: octavawordpressdb.mysql.database.azure.com
